### PR TITLE
Week four assignment

### PR DESCRIPTION
**Pull request by 3lvy**
Hello there, here's my first pull request.

### CODE REVIEW

**Comment by Viralelvy360** [comment]
Hello sorry for the late submission.

**Comment by 3lvy** [comment]
Hello sir.

Sorry for the late submission.

**Comment by 3lvy** [comment]
Hello, sorry for the late submission.

Changed the layout of the AboutMe.md file

**Comment by wangerekaharun** [comment]
> Hello, sorry for the late submission.
> 
> Changed the layout of the AboutMe.md file

You're not yet late. The deadline is tomorrow, that's when we'll be evaluating all the assignments. Feel to make more changes before then.

**Comment by 3lvy** [comment]
Thank you for the clarification and the review @wangerekaharun

**Review by wangerekaharun — APPROVED** [review]
Great work on this. On the skills section if you have projects to showcase you can also attach them. Also, you have too many languages added and it's difficult to master one of them, so please choose your primary language of development and one that you're most comfortable.

If you have follow up questions, feel free to reach out.

**Comment by 3lvy** [comment]
Thank you so much and I will sure do.

**Pull request merged**
